### PR TITLE
fix(Admin Translations) Add translated fields

### PR DESCRIPTION
**Pull request by santostiago**
Replaces hardcoded string in the AA with I18n and adds the french translations.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by santostiago** [comment]
@tsubik there are still a bunch of models to translate, as well as enums and places with hardcoded strings (still didn't check how it work with globalized attributes).
I'll try to finish it during the week.

**Comment by santostiago** [comment]
@tsubik there are still a few places missing: some JS, some partials and some weird spots that I may have missed.
But let's merge it and ask feedback from Sophie. There shouldn't be much more left, and I'll address it in another PR (also, I'm going crazy doing this :P)

**Comment by santostiago** [comment]
Oh.. and there's also the translations of the enums. Any suggestion on how to do that?

**Review by tsubik — APPROVED** [review]

**Comment by tsubik** [comment]
For enums if we need to add translations we could add simple PORO models for each enum (example here https://github.com/Vizzuality/heco-invest/blob/develop/backend/app/models/concerns/enum_model.rb, https://github.com/Vizzuality/heco-invest/blob/develop/backend/app/models/open_call_status.rb) to encapsulate some logic. In locale files I already see one enum translated https://github.com/wri/fti_api/blob/develop/config/locales/en.yml#L37

**Pull request merged**
